#!/bin/bash

# LISTER LES UTILISATEURS
# CHOISIR L'utilisateur a supprimer
# Nettoyer le dossier $HOME de l'utilisateur


# VARIABLES

tab=( $(cat /etc/passwd | awk -F: '{print $ 1}') )
i=0

#==============================
function CLEAN(){

sudo userdel ${tab[$choix]}
if [ -d /home/${tab[$choix]} ];then
	echo "Suppression du /home/${tab[$choix]}"
	sudo rm -rf /home/${tab[$choix]}
fi
sudo sync
}


# MOULINETTE D'AFFICHAGE LISTE USER
while ((${#tab[*]}!=i )) ; do
	echo "$i : ${tab[$i]}"
i=$((i+1))
done

echo "Entrez un chiffre :"
read choix
CLEAN

echo "Travail terminé : utilisateur ${tab[$choix]} supprimé !"
exit






