#!/bin/bash
TITLE="VMWare Registration"
version="0.1"
PASS=$(yad --entry --title="$TITLE $version" --hide-text --text-align=center --text="Password :" --fixed --width=280 --height=120)
echo $PASS|sudo -S clear

# Activation de la license VMWare Workstation Pro 16
function ACTIVATION(){
echo "==> ACTIVATION"
# On active la license directement depuis vmware
echo "ACTIVATION DE LA LICENSE"
echo "License : $LICENSE"
sudo -S /usr/lib/vmware/bin/vmware-vmx-debug --new-sn $LICENSE
echo "LICENSE ACTIVEE"
FINISH
}

function FINISH(){
echo "==> FINISH"
yad --text --title="$TITLE $version" \
	--width=280 --height=120 \
	--text-align=center --text="Votre license\n$LICENSE\nest bien activée" \

}
# Création d'une fenetre pour la saisie de la license
function SAISIE(){
echo "==> SAISIE"
LICENSE=$(yad --entry --width=600 --height=100 \
	--title="$TITLE $version" \
	--entry-label="Entrez votre clé de license : " \
	--entry-text="$KEY")
valret=$?

case $valret in
	0)
	ACTIVATION
	;;
	1)
	echo "EXIT"
	exit
	;;
	255)
	exit
	;;
esac
}

SAISIE
