#! /bin/bash
# 	ZenIso
#	Montage d'iso facile sur voidlinux
#	Créé par Tofdz inspiré par DrNekosan 
#	le 02/12/21
version="1.1.6"

TITLE="ZenIso $version"
optioncompteur="'-f'$compteur"

WDIR=$(pwd)

PASS=$(yad --entry --hide-text --title="ZenIso $version " --text="Entrez votre mot de passe :")
echo $PASS|sudo -S clear
cd $HOME 
echo -e "#====================#"
echo -e "#   $TITLE"
echo -e "#=======#"
function MOUNT(){
touch tmp1
touch tmp2
echo -e "===> MOUNT"
#==> MENU
# MENU SELECTION FICHIER ISO
iso=$(zenity --file-selection --multiple --title "ZenIso $version" \
			--height 500 --width 400 \
			--text "Selectionnez votre ISO" \
	)
echo -e "==> Nom complet du chemin de l'iso:\n" $iso
#==> MENU FIN ======================================
# On recupere le nombre de "/" dans l'adresse de l'iso pour determiner le nom de l'iso
# et donc son repertoire de montage.

# MOULINETTE POUR LE MULTI ISO

# ON CHOPE LES NOMS DES ISO
echo "test de iso : $iso" 
echo $iso > tmp1
sed 's/|/\n/g' tmp1 > tmp2
echo -e "==> Nom complet du chemin de l'iso:\n" $(cat tmp2)
if [ ! -d $HOME/ZenIso ]; then
mkdir $HOME/ZenIso
fi
				
# ON COLLE TOUT DANS UN TABLEAU
unset tab2

while read data2;
do
tab2+=("$data2")
done < tmp2
echo "test tab2 : ${tab2[@]}"

# ON CHOPE LES NOMS DES ISO POUR FAIRE LE POINT DE MONTAGE
compt=${#tab2[*]}; i=0;
unset tabMP
while (($compt!=$i)); do
	compteur=0
	echo -e "TAB2i :${tab2[$i]}"
	compteur=$(echo ${tab2[$i]} | grep -o / | wc -l);
	optioncompteur="-f$(($compteur+1))";echo -e "compteur = $compteur ! optioncompteur : $optioncompteur"
	echo ${tab2[$i]} | cut -d "/" $optioncompteur > tmp1;
	echo -e "--SORTIE NOM --> START"
	cut -d "." -f1 tmp1 > tmp2; echo "tmp2 : $(cat tmp2)"
	cut -d "-" -f1,2 tmp2 > tmp1; echo "tmp3 : $(cat tmp1)"
	sed 's/|/\n/g' tmp1 > tmp2; echo "tmp4 : $(cat tmp2)"
	#sed 's/ /\n/g' tmp4 > $tmp5; echo "tmp5 : $(cat tmp5)"
	sed 's/ /\n/g' tmp2 > tmp1; echo "tmp5 : $(cat tmp1)"
	tabMP[$i]=$(cat tmp1)
	#isodir=$(cat tmp5)
i=$(($i+1));
echo "clic : $i"
done

# TABLEAU tab2 : Contiens le chemin complet pour monter les isos
compt2=${#tab2[*]}; i=0;
while (($i!=$compt2)); do
	# VERIFICATION POINT DE MONTAGE
		echo -e "[${tabMP[$i]}]==> VERIF MP --> $HOME/ZenIso/${tabMP[$i]}"
		echo -e "[${tabMP[$i]}]==> VERIF PRESENCE MP"; 
			if [ ! -d $HOME/ZenIso/${tabMP[$i]} ];then
				echo -e "[${tabMP[$i]}] Création repertoire $HOME/";
				
				
				mkdir $HOME/ZenIso/${tabMP[$i]};
				if [ -d $HOME/ZenIso/${tabMP[$i]} ];then
					echo -e "[${tabMP[$i]}] Repertoire $HOME/ZenIso/${tabMP[$i]} créé !!!";
					echo -e "[${tabMP[$i]}]==> MONTAGE ISO ${tab2[$i]} sur $HOME/ZenIso/${tabMP[$i]}";
					sudo -S mount ${tab2[$i]} $HOME/ZenIso/${tabMP[$i]} -o loop;
				fi
			else
				echo -e "Répertoire déjà présent - veuillez démonter"
			fi
i=$((i+1))
done

MENU
}
function UMOUNT(){
touch tmp1
touch tmp2
echo -e "==> DEMONTAGE :";echo -e "Liste de démontage : $demontage";echo $demontage > tmp1;cat tmp1
# MOULINETTE : EDITION $demontage en liste de sortie pour demonter les isos
echo "*tmp2 ===> sed :suppr | "; sed 's/|/\n/g' tmp1 > tmp2; cat tmp2
echo "*tmp3 ===> sed : suppr espace:"; sed 's/ //g' tmp2 > tmp1; cat tmp1
echo "===*VERIF*==="
# MOULINETTE DE DEMONTAGE
cat tmp1 | while read data;
do
echo -e "UNMOUNT $DATA"
sudo umount $data
sudo rmdir $data
done
MENU
}
function CLEAN(){
echo -e "=>\n==>\n===> CLEAN :"
# MOULINETTE DE SUPPR & VERIF tmp
i=1; f=4
while (($i!=$f)); do
rm tmp$i MPL$i
if [ ! -f tmp$i ];then
echo -e "tmp$i	| DELETED"
else
echo -e "tmp$i	| UNDELETED -> Toujours présent"
fi
if [ ! -f MPL$i ];then
echo -e "MPL$i	| DELETED"
else
echo -e "MPL$i	| UNDELETED -> Toujours présent"
fi
i=$(($i+1))
done

}
function MOULINETTE(){

touch MPL1
touch MPL2
touch MPL3
# lsblk;
# ON RECUPERE LE RESULTAT D'un lsblk pour filtrer les points de montage iso ( /dev/loop )
# On fait une magie pour recuperer la colonne taille et le nom du point de montage


lsblk | grep "loop" > MPL1
sed 's/ /;/g' MPL1 > MPL2
cut -c18- MPL2 > MPL3
cut -d "/" -f2,3,4,5 MPL3 > MPL1
cut -c-8 MPL3 > MPL2
sed 's/;/ /g' MPL2 > MPL3
#cut -d "/" -f2,3,4 MPL1 > MPL2; echo "MPL2" ; cat MPL2 ;
unset taille
unset montage
unset liste
while read -r data1
do
taille+=("$data1")
done < MPL3
while read -r data2
do
montage+=(/"$data2")
done < MPL1
i=0
compteur=${#montage[*]}
while (($compteur!=$i));
do
liste+=(FALSE "${taille[$i]}" "${montage[$i]}")
i=$(($i+1));
done 
}
function DESTROYALL(){

sudo -S umount $HOME/ZenIso/*
rm -Rf $HOME/ZenIso
MENU
}
function MENU(){
CLEAN
MOULINETTE

echo -e "================================"
echo -e "==> MENU YAD"
demontage=$(yad --width 400 --height 400 --print-column 3 \
				--list --checklist --title="ZenIso $version" \
				--image=tools-media-optical-burn-image \
				--button="Quit:0" --button=" ALL:3" \
				--button=":1" --button=" :2" \
				--text="Gestion montage Fichiers ISO" \
				--entry-label=" Liste iso monté(s) : " \
				--column="  " --column="  " --column="Point de montage :" \
				"${liste[@]}" \
				)
valret=$?
#if [[ $ret -eq 0 ]] && exit 0
if [[ $ret -eq 1 ]]; then
	MOUNT
fi

case $valret in
	0)
	CLEAN
	exit
	;;
	1)
	MOUNT
	;;
	2)
	UMOUNT
	;;
	3)
	DESTROYALL
	;;
	255)
	CLEAN
	exit
	;;
esac
}
MENU